allow-newer: true
extra-deps:
- cryptohash-sha256-0.11.100.1
- echo-0.1.3
- ed25519-0.0.5.0
- mintty-0.1.1
- parsec-3.1.13.0
# - dhall-1.16.1
- git: https://github.com/eta-lang/dhall-haskell.git
  commit: dd92735677ac093222b02eab88d5cb5f88c163fd
- ansi-terminal-0.7.1.1
- ansi-wl-pprint-0.6.8.2
- cryptonite-0.24
- formatting-6.3.2
- megaparsec-6.4.1
- parser-combinators-0.4.0
- optparse-generic-1.3.0
- optparse-applicative-0.14.0.0
- Only-0.1
- memory-0.14.14
- basement-0.0.6
- prettyprinter-1.2.0.1
- prettyprinter-ansi-terminal-1.1.1.2
- directory-1.3.1.0
- foundation-0.0.19
- process-1.2.3.0
- repline-0.1.7.0
- haskeline-0.7.4.2
- insert-ordered-containers-0.2.1.0
- aeson-1.2.3.0
- th-abstraction-0.2.6.0
- hashable-1.2.7.0
- Diff-0.3.4
- cborg-0.2.0.0
- serialise-0.2.0.0
resolver: lts-6.27
flags:
  etlas-cabal:
    parsec: true
  etlas:
    parsec: true
  mintty:
    win32-2-5: false
packages:
- etlas-cabal/
- dhall-to-etlas/
- etlas/
- hackage-security/hackage-security
